{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postgres-ha.fullname" . }}
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "postgres-ha.matchLabels" . | nindent 6 }}
{{- end }}
